webtalk_init -webtalk_dir H:/GitRepos/CS152B-Projects/Lab1-Vivado/RMJ-Lab1.sim/16_bit_alu_sim/behav/xsim/xsim.dir/ut_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct 14 00:05:24 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f1d9b629-dd1f-4b3b-a9ef-7c2a2b65590a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "83025e135f08475dbfd889eadf1e8936" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "125 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2667613133 -regid "" -xml H:/GitRepos/CS152B-Projects/Lab1-Vivado/RMJ-Lab1.sim/16_bit_alu_sim/behav/xsim/xsim.dir/ut_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/GitRepos/CS152B-Projects/Lab1-Vivado/RMJ-Lab1.sim/16_bit_alu_sim/behav/xsim/xsim.dir/ut_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/GitRepos/CS152B-Projects/Lab1-Vivado/RMJ-Lab1.sim/16_bit_alu_sim/behav/xsim/xsim.dir/ut_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
